return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "biome",
        "copilot-language-server",
        "css-lsp",
        "docker-language-server",
        "eslint-lsp",
        "fish-lsp",
        "gh-actions-language-server",
        "html-lsp",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "prisma-language-server",
        "ruff",
        "rust-analyzer",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "taplo",
        "tree-sitter-cli",
        "tsp-server",
        "typescript-language-server",
        "vtsls",
        "yaml-language-server",
      },
    },
  },
}
